import type { NextPage } from 'next'
import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

interface Props {
  data: string
}

const Home: NextPage<Props> = ({ data }) => {
  const [isShowingButton, setIsShowingButton] = useState(true);

  return (
    <div className={styles.container}>
      <Head>
        <title>
          Minimal example of Next.js 12.0.2/ESM Vercel production bug
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.buttonContainer}>

          <p className={styles.server}>
            <strong>Server-side data:</strong>
            <br />
            {data}
          </p>

          <AnimatePresence>
            {isShowingButton
              ? <motion.div
                className={styles.button}
                onClick={() => setIsShowingButton(false)}
                initial={{ top: '-1rem', opacity: 0 }}
                animate={{ top: '0rem', opacity: 1 }}
                exit={{ top: '1rem', opacity: 0}}
              >
                Hide Button
              </motion.div>
              : <motion.div
                className={`${styles.button} ${styles.buttonAlt}`}
                onClick={() => setIsShowingButton(true)}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
              >
                Restore button
              </motion.div>}
          </AnimatePresence>

        </div>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

Home.getInitialProps = async (): Promise<Props> => {
  return {
    data: 'SERVER-GENERATED RESULT',
  }
};

export default Home
