import type { NextPage } from 'next'
// @ts-ignore
const { readFileSync } = __non_webpack_require__('fs');
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const FONT_NAME = 'marcellus/MarcellusSC-Regular.woff2';

interface Props {
  fontPath: string
  fontData: string
}

const Home: NextPage<Props> = ({ fontPath, fontData }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>
          Minimal example of Next.js 12.0.2/ESM Vercel production bug
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.buttonContainer}>

          <p className={styles.server}>
            <strong>Server-side data:</strong>
            <br />
            {fontPath}
            {fontData}
          </p>

        </div>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

Home.getInitialProps = async (): Promise<Props> => {
  const fontPath = `${process.cwd()}/fonts/${FONT_NAME}`;
  const fontData = readFileSync(fontPath).toString('base64');
  return {
    fontPath,
    fontData,
  }
};

export default Home
